export type RegistryPage = {
  odin: string;
  page: string;
};

export type RegistrySection = {
  title: string;
  pages: RegistryPage[];
};

export type PlatformRegistry = {
  platform: string;
  mission: string;
  count: number;
  sections: RegistrySection[];
};

export const masterPageRegistry: PlatformRegistry[] = [
  {
    platform: 'ONEGODIAN.ORG',
    mission: 'Identity • Community • Education • Archives',
    count: 36,
    sections: [
      {
        title: 'Core Pages',
        pages: [
          { odin: 'ODIN-ORG-0001', page: 'Home' },
          { odin: 'ODIN-ORG-0002', page: 'About OneGodian' },
          { odin: 'ODIN-ORG-0003', page: 'What Is OneGodian' },
          { odin: 'ODIN-ORG-0004', page: 'Founder' },
          { odin: 'ODIN-ORG-0005', page: 'Mission' },
          { odin: 'ODIN-ORG-0006', page: 'Vision' },
          { odin: 'ODIN-ORG-0007', page: 'Community' },
          { odin: 'ODIN-ORG-0008', page: 'Membership' },
          { odin: 'ODIN-ORG-0009', page: 'Identity' },
          { odin: 'ODIN-ORG-0010', page: 'OneGodian Calendar' },
          { odin: 'ODIN-ORG-0011', page: 'OneGodian Time' },
          { odin: 'ODIN-ORG-0012', page: 'OneGodian Months' },
          { odin: 'ODIN-ORG-0013', page: 'Live Clock' },
          { odin: 'ODIN-ORG-0014', page: 'History' },
          { odin: 'ODIN-ORG-0015', page: 'Archives' },
          { odin: 'ODIN-ORG-0016', page: 'Constitution' },
          { odin: 'ODIN-ORG-0017', page: 'Declaration' },
          { odin: 'ODIN-ORG-0018', page: 'Divine 9' },
          { odin: 'ODIN-ORG-0019', page: 'Remembrance' },
          { odin: 'ODIN-ORG-0020', page: 'Remember Campaign' },
          { odin: 'ODIN-ORG-0021', page: 'Contributors' },
          { odin: 'ODIN-ORG-0022', page: 'Volunteer' },
          { odin: 'ODIN-ORG-0023', page: 'Donate' },
          { odin: 'ODIN-ORG-0024', page: 'Community Projects' },
          { odin: 'ODIN-ORG-0025', page: 'Events' },
          { odin: 'ODIN-ORG-0026', page: 'News' },
          { odin: 'ODIN-ORG-0027', page: 'Blog' },
          { odin: 'ODIN-ORG-0028', page: 'Media Center' },
          { odin: 'ODIN-ORG-0029', page: 'FAQ' },
          { odin: 'ODIN-ORG-0030', page: 'Contact' },
          { odin: 'ODIN-ORG-0031', page: 'Privacy Policy' },
          { odin: 'ODIN-ORG-0032', page: 'Terms' },
          { odin: 'ODIN-ORG-0033', page: 'Accessibility' },
          { odin: 'ODIN-ORG-0034', page: 'Site Map' },
          { odin: 'ODIN-ORG-0035', page: 'Support' },
          { odin: 'ODIN-ORG-0036', page: 'Portal' },
        ],
      },
    ],
  },
  {
    platform: 'ONEGODIAN.COM',
    mission: 'Commerce • Services • Revenue',
    count: 72,
    sections: [
      {
        title: 'Main Store',
        pages: [
          { odin: 'ODIN-COM-0001', page: 'Home' },
          { odin: 'ODIN-COM-0002', page: 'Shop' },
          { odin: 'ODIN-COM-0003', page: 'Cart' },
          { odin: 'ODIN-COM-0004', page: 'Checkout' },
          { odin: 'ODIN-COM-0005', page: 'My Account' },
          { odin: 'ODIN-COM-0006', page: 'Orders' },
          { odin: 'ODIN-COM-0007', page: 'Wishlist' },
          { odin: 'ODIN-COM-0008', page: 'Customer Dashboard' },
        ],
      },
      {
        title: 'Product Stores',
        pages: [
          { odin: 'ODIN-COM-0010', page: 'Book Store' },
          { odin: 'ODIN-COM-0011', page: 'Music Store' },
          { odin: 'ODIN-COM-0012', page: 'Course Store' },
          { odin: 'ODIN-COM-0013', page: 'Digital Download Store' },
          { odin: 'ODIN-COM-0014', page: 'Apparel Store' },
          { odin: 'ODIN-COM-0015', page: 'Poster Store' },
          { odin: 'ODIN-COM-0016', page: 'Scroll Store' },
          { odin: 'ODIN-COM-0017', page: 'Certification Store' },
          { odin: 'ODIN-COM-0018', page: 'Software Store' },
          { odin: 'ODIN-COM-0019', page: 'Services Store' },
        ],
      },
      {
        title: 'Services',
        pages: [
          { odin: 'ODIN-COM-0020', page: 'Website Audit' },
          { odin: 'ODIN-COM-0021', page: 'WordPress Setup' },
          { odin: 'ODIN-COM-0022', page: 'WooCommerce Setup' },
          { odin: 'ODIN-COM-0023', page: 'LMS Setup' },
          { odin: 'ODIN-COM-0024', page: 'Membership Setup' },
          { odin: 'ODIN-COM-0025', page: 'SEO Optimization' },
          { odin: 'ODIN-COM-0026', page: 'Content Development' },
          { odin: 'ODIN-COM-0027', page: 'Digital Strategy' },
          { odin: 'ODIN-COM-0028', page: 'Business Consulting' },
          { odin: 'ODIN-COM-0029', page: 'Economic Development Consulting' },
        ],
      },
      {
        title: 'Education',
        pages: [
          { odin: 'ODIN-COM-0030', page: 'Introduction to OneGodian' },
          { odin: 'ODIN-COM-0031', page: 'OMOS Foundations' },
          { odin: 'ODIN-COM-0032', page: 'Workforce Development' },
          { odin: 'ODIN-COM-0033', page: 'Community Development Fundamentals' },
          { odin: 'ODIN-COM-0034', page: 'Economic Development Fundamentals' },
          { odin: 'ODIN-COM-0035', page: 'Leadership Certification' },
          { odin: 'ODIN-COM-0036', page: 'Companion Certification' },
          { odin: 'ODIN-COM-0037', page: 'Translation Certification' },
          { odin: 'ODIN-COM-0038', page: 'Technology Certification' },
        ],
      },
      {
        title: 'Tools',
        pages: [
          { odin: 'ODIN-COM-0040', page: 'Belief Mapper' },
          { odin: 'ODIN-COM-0041', page: 'Purpose Finder' },
          { odin: 'ODIN-COM-0042', page: 'Relationship Alignment' },
          { odin: 'ODIN-COM-0043', page: 'OMOS Alignment Score' },
          { odin: 'ODIN-COM-0044', page: 'OneGodian Time Tools' },
          { odin: 'ODIN-COM-0045', page: 'Certificate Verification' },
        ],
      },
      {
        title: 'Company',
        pages: [
          { odin: 'ODIN-COM-0050', page: 'About' },
          { odin: 'ODIN-COM-0051', page: 'Founder' },
          { odin: 'ODIN-COM-0052', page: 'Services' },
          { odin: 'ODIN-COM-0053', page: 'Partners' },
          { odin: 'ODIN-COM-0054', page: 'Affiliates' },
          { odin: 'ODIN-COM-0055', page: 'Careers' },
          { odin: 'ODIN-COM-0056', page: 'Media Center' },
          { odin: 'ODIN-COM-0057', page: 'Contact' },
        ],
      },
      {
        title: 'Members',
        pages: [
          { odin: 'ODIN-COM-0060', page: 'Member Dashboard' },
          { odin: 'ODIN-COM-0061', page: 'Certificates' },
          { odin: 'ODIN-COM-0062', page: 'Downloads' },
          { odin: 'ODIN-COM-0063', page: 'Billing' },
          { odin: 'ODIN-COM-0064', page: 'Membership Directory' },
          { odin: 'ODIN-COM-0065', page: 'Community Hub' },
        ],
      },
      {
        title: 'Legal',
        pages: [
          { odin: 'ODIN-COM-0070', page: 'Terms' },
          { odin: 'ODIN-COM-0071', page: 'Privacy' },
          { odin: 'ODIN-COM-0072', page: 'Disclaimer' },
        ],
      },
    ],
  },
  {
    platform: 'U.ONEGODIAN.COM',
    mission: 'University of OneGodian™',
    count: 25,
    sections: [
      {
        title: 'Core Pages',
        pages: [
          { odin: 'ODIN-U-0001', page: 'Home' },
          { odin: 'ODIN-U-0002', page: 'Catalog' },
          { odin: 'ODIN-U-0003', page: 'Courses' },
          { odin: 'ODIN-U-0004', page: 'Programs' },
          { odin: 'ODIN-U-0005', page: 'Certifications' },
          { odin: 'ODIN-U-0006', page: 'Instructors' },
          { odin: 'ODIN-U-0007', page: 'Students' },
          { odin: 'ODIN-U-0008', page: 'Dashboard' },
          { odin: 'ODIN-U-0009', page: 'LMS' },
          { odin: 'ODIN-U-0010', page: 'My Learning' },
          { odin: 'ODIN-U-0011', page: 'Certificates' },
          { odin: 'ODIN-U-0012', page: 'Transcript' },
          { odin: 'ODIN-U-0013', page: 'Workforce Development' },
          { odin: 'ODIN-U-0014', page: 'Community Development' },
          { odin: 'ODIN-U-0015', page: 'Technology' },
          { odin: 'ODIN-U-0016', page: 'Leadership' },
          { odin: 'ODIN-U-0017', page: 'Translation' },
          { odin: 'ODIN-U-0018', page: 'Companion' },
          { odin: 'ODIN-U-0019', page: 'Economic Development' },
          { odin: 'ODIN-U-0020', page: 'Enrollment' },
          { odin: 'ODIN-U-0021', page: 'Tuition' },
          { odin: 'ODIN-U-0022', page: 'FAQ' },
          { odin: 'ODIN-U-0023', page: 'Contact' },
          { odin: 'ODIN-U-0024', page: 'Portal' },
          { odin: 'ODIN-U-0025', page: 'Library' },
        ],
      },
    ],
  },
  {
    platform: 'GALAXY.ONEGODIAN.COM',
    mission: 'OneGodian Galaxy™',
    count: 32,
    sections: [
      {
        title: 'Core Pages',
        pages: [
          { odin: 'ODIN-GAL-0001', page: 'Home' },
          { odin: 'ODIN-GAL-0002', page: 'Galaxy Overview' },
          { odin: 'ODIN-GAL-0003', page: 'Worlds' },
          { odin: 'ODIN-GAL-0004', page: 'Planet Onegodia' },
          { odin: 'ODIN-GAL-0005', page: 'Divine 9' },
          { odin: 'ODIN-GAL-0006', page: 'Lore' },
          { odin: 'ODIN-GAL-0007', page: 'Stories' },
          { odin: 'ODIN-GAL-0008', page: 'Characters' },
          { odin: 'ODIN-GAL-0009', page: 'Timeline' },
          { odin: 'ODIN-GAL-0010', page: 'Maps' },
          { odin: 'ODIN-GAL-0011', page: 'Civilizations' },
          { odin: 'ODIN-GAL-0012', page: 'Species' },
          { odin: 'ODIN-GAL-0013', page: 'Realms' },
          { odin: 'ODIN-GAL-0014', page: 'Archives' },
          { odin: 'ODIN-GAL-0015', page: 'Encyclopedia' },
          { odin: 'ODIN-GAL-0016', page: 'Visual Gallery' },
          { odin: 'ODIN-GAL-0017', page: 'Posters' },
          { odin: 'ODIN-GAL-0018', page: 'Downloads' },
          { odin: 'ODIN-GAL-0019', page: 'Media' },
          { odin: 'ODIN-GAL-0020', page: 'Creator Hub' },
          { odin: 'ODIN-GAL-0021', page: 'Community' },
          { odin: 'ODIN-GAL-0022', page: 'Membership' },
          { odin: 'ODIN-GAL-0023', page: 'Marketplace' },
          { odin: 'ODIN-GAL-0024', page: 'NFTs & Collectibles' },
          { odin: 'ODIN-GAL-0025', page: 'Books' },
          { odin: 'ODIN-GAL-0026', page: 'Comics' },
          { odin: 'ODIN-GAL-0027', page: 'Games' },
          { odin: 'ODIN-GAL-0028', page: 'Events' },
          { odin: 'ODIN-GAL-0029', page: 'News' },
          { odin: 'ODIN-GAL-0030', page: 'Contact' },
          { odin: 'ODIN-GAL-0031', page: 'FAQ' },
          { odin: 'ODIN-GAL-0032', page: 'Portal' },
        ],
      },
    ],
  },
  {
    platform: 'CAPITAL.ONEGODIAN.COM',
    mission: 'ONEGODIAN Capital™',
    count: 55,
    sections: [
      {
        title: 'Capital Core',
        pages: [
          { odin: 'ODIN-CAP-0001', page: 'Home' },
          { odin: 'ODIN-CAP-0002', page: 'Capital Dashboard' },
          { odin: 'ODIN-CAP-0003', page: 'Disclosure Center' },
          { odin: 'ODIN-CAP-0004', page: 'Investor Portal' },
          { odin: 'ODIN-CAP-0005', page: 'Contributor Portal' },
          { odin: 'ODIN-CAP-0006', page: 'Capital Reports' },
          { odin: 'ODIN-CAP-0007', page: 'Asset Registry' },
          { odin: 'ODIN-CAP-0008', page: 'Instruments' },
          { odin: 'ODIN-CAP-0009', page: 'Funding Rounds' },
          { odin: 'ODIN-CAP-0010', page: 'Due Diligence' },
        ],
      },
      {
        title: 'INSTRYX™',
        pages: [
          { odin: 'ODIN-CAP-0011', page: 'Instryx Home' },
          { odin: 'ODIN-CAP-0012', page: 'Runtime' },
          { odin: 'ODIN-CAP-0013', page: 'Readiness' },
          { odin: 'ODIN-CAP-0014', page: 'Investor Intelligence' },
          { odin: 'ODIN-CAP-0015', page: 'Execution Analytics' },
          { odin: 'ODIN-CAP-0016', page: 'Asset Scoring' },
          { odin: 'ODIN-CAP-0017', page: 'Reporting' },
        ],
      },
      {
        title: 'ZOLFI™',
        pages: [
          { odin: 'ODIN-CAP-0020', page: 'Zolfi Home' },
          { odin: 'ODIN-CAP-0021', page: 'Security' },
          { odin: 'ODIN-CAP-0022', page: 'Smart Contracts' },
          { odin: 'ODIN-CAP-0023', page: 'Verification' },
          { odin: 'ODIN-CAP-0024', page: 'Post Quantum Readiness' },
        ],
      },
      {
        title: 'ODC™',
        pages: [
          { odin: 'ODIN-CAP-0030', page: 'ODC Dashboard' },
          { odin: 'ODIN-CAP-0031', page: 'ODC Swap' },
          { odin: 'ODIN-CAP-0032', page: 'ODC Stake' },
          { odin: 'ODIN-CAP-0033', page: 'ODC Bridge' },
          { odin: 'ODIN-CAP-0034', page: 'ODC Explorer' },
          { odin: 'ODIN-CAP-0035', page: 'ODC Governance' },
        ],
      },
      {
        title: 'QRV™',
        pages: [
          { odin: 'ODIN-CAP-0040', page: 'QRV Home' },
          { odin: 'ODIN-CAP-0041', page: 'Verification' },
          { odin: 'ODIN-CAP-0042', page: 'Certificates' },
          { odin: 'ODIN-CAP-0043', page: 'Registry' },
          { odin: 'ODIN-CAP-0044', page: 'APIs' },
          { odin: 'ODIN-CAP-0045', page: 'Documentation' },
        ],
      },
      {
        title: 'Capital Operations',
        pages: [
          { odin: 'ODIN-CAP-0050', page: 'Notes' },
          { odin: 'ODIN-CAP-0051', page: 'Bonds' },
          { odin: 'ODIN-CAP-0052', page: 'Revenue Participation' },
          { odin: 'ODIN-CAP-0053', page: 'Licensing' },
          { odin: 'ODIN-CAP-0054', page: 'Membership Revenue' },
          { odin: 'ODIN-CAP-0055', page: 'Asset Marketplace' },
        ],
      },
    ],
  },
];

export const masterPageRegistrySummary = {
  version: 'Production Tracking Registry v1',
  purpose: 'Track all major pages, routes, hubs, and commercial destinations across the OneGodian ecosystem using ODIN page identifiers.',
  total: masterPageRegistry.reduce((sum, platform) => sum + platform.count, 0),
  expansionTargets: [
    'OMOS.OneGodian.com',
    'App.OneGodian.com',
    'OBP1.OneGodian.org',
    'Time.OneGodian.org',
    'QuantumOHI.com',
    'QRV.Network',
  ],
};
